image: node:latest

cache:
  paths:
    - node_modules/

run_unit_tests:
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng test --single-run=true --browsers PhantomJS --watch=false
